# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_base.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo', 'HelloSayer']

# %% ../nbs/00_base.ipynb 2
def say_hello(to):
    "Day hello to sombody"
    return f'Hello {to}!'

# %% ../nbs/00_base.ipynb 4
def foo(): pass

# %% ../nbs/00_base.ipynb 6
#| export

# %% ../nbs/00_base.ipynb 7
class HelloSayer:
    "Say hello to `to` using say_hello"
    def __init__(self, to): self.to = to
    
    def say(self):
        "Do the saying"
        return say_hello(self.to)
